# Generated by Django 6.0.5 on 2026-08-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='media_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
