# Generated by Django 6.0.5 on 2026-08-06 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=500, unique=True)),
                ('device_type', models.CharField(default='android', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_role', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('APPOINTMENT', 'Appointment'), ('COURSE', 'Course'), ('COMMUNITY', 'Community'), ('PROFILE', 'Profile'), ('KNOWLEDGE_HUB', 'Knowledge Hub'), ('MIND_GAME', 'Mind Game'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
