# Generated by Django 6.0.5 on 2026-08-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('APPOINTMENT', 'Appointment'), ('COURSE', 'Course'), ('COMMUNITY', 'Community'), ('PROFILE', 'Profile'), ('KNOWLEDGE_HUB', 'Knowledge Hub'), ('MIND_GAME', 'Mind Game'), ('ASSESSMENT', 'Assessment'), ('PAYMENT', 'Payment'), ('SECURITY', 'Security'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
    ]
