# Generated by Django 6.0.7 on 2026-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_created_at_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='course_media/'),
        ),
        migrations.AddField(
            model_name='course',
            name='media_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
